import type { AppData, PageMetric, Project, SearchQueryMetric } from "@/lib/types";

export type AggregatedRow = {
  key: string;
  clicks: number;
  impressions: number;
  ctr: number;
  avgPosition: number;
};

function aggregate<T extends { clicks: number; impressions: number; avgPosition: number }>(
  rows: T[],
  keyOf: (row: T) => string,
): AggregatedRow[] {
  const byKey = new Map<string, { clicks: number; impressions: number; positionWeighted: number }>();

  for (const row of rows) {
    const key = keyOf(row);
    const existing = byKey.get(key) ?? { clicks: 0, impressions: 0, positionWeighted: 0 };
    existing.clicks += row.clicks;
    existing.impressions += row.impressions;
    existing.positionWeighted += row.avgPosition * row.impressions;
    byKey.set(key, existing);
  }

  return [...byKey.entries()]
    .map(([key, value]) => ({
      key,
      clicks: value.clicks,
      impressions: value.impressions,
      ctr: value.impressions > 0 ? value.clicks / value.impressions : 0,
      avgPosition: value.impressions > 0 ? value.positionWeighted / value.impressions : 0,
    }))
    .sort((a, b) => b.impressions - a.impressions);
}

export function aggregatePagesByUrl(pages: PageMetric[]): AggregatedRow[] {
  return aggregate(pages, (row) => row.page);
}

export function aggregateQueriesByText(queries: SearchQueryMetric[]): AggregatedRow[] {
  return aggregate(queries, (row) => row.query);
}

function formatPercent(value: number): string {
  return `${(value * 100).toFixed(2)}%`;
}

function formatRow(row: AggregatedRow): string {
  return `${row.key} | clicks: ${row.clicks} | impr: ${row.impressions} | ctr: ${formatPercent(row.ctr)} | avgPos: ${row.avgPosition.toFixed(1)}`;
}

export function buildGscReportMarkdown(
  data: AppData,
  project: Project,
  options: { topPages?: number; topQueries?: number } = {},
): string {
  const topPages = options.topPages ?? 20;
  const topQueries = options.topQueries ?? 30;

  const queries = data.searchQueries.filter((row) => row.projectId === project.id);
  const pages = data.pageMetrics.filter((row) => row.projectId === project.id);
  const snapshots = data.metricSnapshots.filter((row) => row.projectId === project.id && row.source === "gsc");

  const dates = [...new Set([...queries, ...pages].map((row) => row.date))].sort();
  const rangeStart = dates[0] ?? "n/a";
  const rangeEnd = dates[dates.length - 1] ?? "n/a";

  const totals = snapshots.reduce(
    (acc, row) => ({
      clicks: acc.clicks + (row.clicks ?? 0),
      impressions: acc.impressions + (row.impressions ?? 0),
      positionWeighted: acc.positionWeighted + (row.avgPosition ?? 0) * (row.impressions ?? 0),
    }),
    { clicks: 0, impressions: 0, positionWeighted: 0 },
  );
  const avgPosition = totals.impressions > 0 ? totals.positionWeighted / totals.impressions : 0;
  const ctr = totals.impressions > 0 ? totals.clicks / totals.impressions : 0;

  const pageRows = aggregatePagesByUrl(pages).slice(0, topPages);
  const queryRows = aggregateQueriesByText(queries).slice(0, topQueries);

  const lines: string[] = [];
  lines.push(`# ${project.name} - GSC report - ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push("## Scope");
  lines.push("");
  lines.push("Project:");
  lines.push("");
  lines.push("```txt");
  lines.push(project.websiteUrl ?? project.slug);
  lines.push("```");
  lines.push("");
  lines.push("Source:");
  lines.push("");
  lines.push("```txt");
  lines.push(`Google Search Console: ${project.gscProperty ?? "(not configured)"}`);
  lines.push("```");
  lines.push("");
  lines.push("Period covered by current data:");
  lines.push("");
  lines.push("```txt");
  lines.push(`${rangeStart} -> ${rangeEnd}`);
  lines.push("```");
  lines.push("");
  lines.push("## GSC summary");
  lines.push("");
  lines.push("```txt");
  lines.push(`Clicks:        ${totals.clicks.toLocaleString("it-IT")}`);
  lines.push(`Impressions:   ${totals.impressions.toLocaleString("it-IT")}`);
  lines.push(`CTR:           ${formatPercent(ctr)}`);
  lines.push(`Avg position:  ${avgPosition.toFixed(1)}`);
  lines.push("```");
  lines.push("");
  lines.push(`## Top pages by impressions (top ${pageRows.length})`);
  lines.push("");
  lines.push("```txt");
  for (const row of pageRows) lines.push(formatRow(row));
  lines.push("```");
  lines.push("");
  lines.push(`## Top queries by impressions (top ${queryRows.length})`);
  lines.push("");
  lines.push("```txt");
  for (const row of queryRows) lines.push(formatRow(row));
  lines.push("```");
  lines.push("");
  lines.push("## Notes");
  lines.push("");
  lines.push("```txt");
  lines.push("This is a raw data dump generated by `pnpm run report`.");
  lines.push("Use it as the data section of a full report; add findings, priorities");
  lines.push("and recommended actions by hand (or ask the assistant to extend it).");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}
