import type { AppData, AppKeywordMetric, PageMetric, Project, SearchQueryMetric } from "@/lib/types";

export type AggregatedRow = {
  key: string;
  clicks: number;
  impressions: number;
  ctr: number;
  avgPosition: number;
};

function aggregate<T extends { clicks: number; impressions: number; avgPosition: number }>(
  rows: T[],
  keyOf: (row: T) => string,
): AggregatedRow[] {
  const byKey = new Map<string, { clicks: number; impressions: number; positionWeighted: number }>();

  for (const row of rows) {
    const key = keyOf(row);
    const existing = byKey.get(key) ?? { clicks: 0, impressions: 0, positionWeighted: 0 };
    existing.clicks += row.clicks;
    existing.impressions += row.impressions;
    existing.positionWeighted += row.avgPosition * row.impressions;
    byKey.set(key, existing);
  }

  return [...byKey.entries()]
    .map(([key, value]) => ({
      key,
      clicks: value.clicks,
      impressions: value.impressions,
      ctr: value.impressions > 0 ? value.clicks / value.impressions : 0,
      avgPosition: value.impressions > 0 ? value.positionWeighted / value.impressions : 0,
    }))
    .sort((a, b) => b.impressions - a.impressions);
}

export function aggregatePagesByUrl(pages: PageMetric[]): AggregatedRow[] {
  return aggregate(pages, (row) => row.page);
}

export function aggregateQueriesByText(queries: SearchQueryMetric[]): AggregatedRow[] {
  return aggregate(queries, (row) => row.query);
}

function formatPercent(value: number): string {
  return `${(value * 100).toFixed(2)}%`;
}

function formatRow(row: AggregatedRow): string {
  return `${row.key} | clicks: ${row.clicks} | impr: ${row.impressions} | ctr: ${formatPercent(row.ctr)} | avgPos: ${row.avgPosition.toFixed(1)}`;
}

export function buildGscReportMarkdown(
  data: AppData,
  project: Project,
  options: { topPages?: number; topQueries?: number } = {},
): string {
  const topPages = options.topPages ?? 20;
  const topQueries = options.topQueries ?? 30;

  const queries = data.searchQueries.filter((row) => row.projectId === project.id);
  const pages = data.pageMetrics.filter((row) => row.projectId === project.id);
  const snapshots = data.metricSnapshots.filter((row) => row.projectId === project.id && row.source === "gsc");

  const dates = [...new Set([...queries, ...pages].map((row) => row.date))].sort();
  const rangeStart = dates[0] ?? "n/a";
  const rangeEnd = dates[dates.length - 1] ?? "n/a";

  const totals = snapshots.reduce(
    (acc, row) => ({
      clicks: acc.clicks + (row.clicks ?? 0),
      impressions: acc.impressions + (row.impressions ?? 0),
      positionWeighted: acc.positionWeighted + (row.avgPosition ?? 0) * (row.impressions ?? 0),
    }),
    { clicks: 0, impressions: 0, positionWeighted: 0 },
  );
  const avgPosition = totals.impressions > 0 ? totals.positionWeighted / totals.impressions : 0;
  const ctr = totals.impressions > 0 ? totals.clicks / totals.impressions : 0;

  const pageRows = aggregatePagesByUrl(pages).slice(0, topPages);
  const queryRows = aggregateQueriesByText(queries).slice(0, topQueries);

  const lines: string[] = [];
  lines.push(`# ${project.name} - GSC report - ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push("## Scope");
  lines.push("");
  lines.push("Project:");
  lines.push("");
  lines.push("```txt");
  lines.push(project.websiteUrl ?? project.slug);
  lines.push("```");
  lines.push("");
  lines.push("Source:");
  lines.push("");
  lines.push("```txt");
  lines.push(`Google Search Console: ${project.gscProperty ?? "(not configured)"}`);
  lines.push("```");
  lines.push("");
  lines.push("Period covered by current data:");
  lines.push("");
  lines.push("```txt");
  lines.push(`${rangeStart} -> ${rangeEnd}`);
  lines.push("```");
  lines.push("");
  lines.push("## GSC summary");
  lines.push("");
  lines.push("```txt");
  lines.push(`Clicks:        ${totals.clicks.toLocaleString("it-IT")}`);
  lines.push(`Impressions:   ${totals.impressions.toLocaleString("it-IT")}`);
  lines.push(`CTR:           ${formatPercent(ctr)}`);
  lines.push(`Avg position:  ${avgPosition.toFixed(1)}`);
  lines.push("```");
  lines.push("");
  lines.push(`## Top pages by impressions (top ${pageRows.length})`);
  lines.push("");
  lines.push("```txt");
  for (const row of pageRows) lines.push(formatRow(row));
  lines.push("```");
  lines.push("");
  lines.push(`## Top queries by impressions (top ${queryRows.length})`);
  lines.push("");
  lines.push("```txt");
  for (const row of queryRows) lines.push(formatRow(row));
  lines.push("```");
  lines.push("");
  lines.push("## Notes");
  lines.push("");
  lines.push("```txt");
  lines.push("This is a raw data dump generated by `pnpm run report`.");
  lines.push("Use it as the data section of a full report; add findings, priorities");
  lines.push("and recommended actions by hand (or ask the assistant to extend it).");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

function formatKeywordRow(row: AppKeywordMetric): string {
  const rank = row.appRank == null ? "-" : `#${row.appRank}`;
  return (
    `${row.keyword.padEnd(30)} | ${row.country.toUpperCase()} | ` +
    `pop: ${row.popularityScore} | diff: ${row.difficultyScore} (${row.difficultyLabel ?? "?"}) | ` +
    `opp: ${row.opportunityScore} | ${row.classification ?? "?"} | rank: ${rank}`
  );
}

function formatTrendRows(previous: AppKeywordMetric[], latest: AppKeywordMetric[]): string[] {
  const previousByKey = new Map(previous.map((row) => [`${row.country.toLowerCase()}:${row.keyword.toLowerCase()}`, row]));
  const lines: string[] = [];

  for (const row of [...latest].sort((a, b) => b.opportunityScore - a.opportunityScore)) {
    const before = previousByKey.get(`${row.country.toLowerCase()}:${row.keyword.toLowerCase()}`);
    if (!before) continue;

    const rankDelta = formatDelta(before.appRank ?? null, row.appRank ?? null, { lowerIsBetter: true });
    const oppDelta = formatDelta(before.opportunityScore, row.opportunityScore, { lowerIsBetter: false });
    const popDelta = formatDelta(before.popularityScore, row.popularityScore, { lowerIsBetter: false });
    const rank = row.appRank == null ? "-" : `#${row.appRank}`;

    lines.push(
      `${row.keyword.padEnd(30)} | ${row.country.toUpperCase()} | ` +
        `rank: ${rank} (${rankDelta}) | opp: ${row.opportunityScore} (${oppDelta}) | pop: ${row.popularityScore} (${popDelta})`,
    );
  }

  if (lines.length === 0) lines.push("No keywords found in both snapshots.");
  return lines;
}

function formatDelta(before: number | null, after: number | null, options: { lowerIsBetter: boolean }): string {
  if (before == null || after == null) return "n/a";
  const diff = after - before;
  if (diff === 0) return "=";
  const improved = options.lowerIsBetter ? diff < 0 : diff > 0;
  const arrow = improved ? "up" : "down";
  return `${arrow} ${diff > 0 ? "+" : ""}${diff}`;
}

export function buildAsoReportMarkdown(data: AppData, project: Project): string {
  const keywords = data.appKeywords
    .filter((row) => row.projectId === project.id)
    .sort((a, b) => b.opportunityScore - a.opportunityScore || b.date.localeCompare(a.date));

  const dates = [...new Set(keywords.map((row) => row.date))].sort();
  const latestDate = dates[dates.length - 1];
  const latest = keywords.filter((row) => row.date === latestDate);

  const byClassification = new Map<string, AppKeywordMetric[]>();
  for (const row of latest) {
    const list = byClassification.get(row.classification ?? "unknown") ?? [];
    list.push(row);
    byClassification.set(row.classification ?? "unknown", list);
  }

  const lines: string[] = [];
  lines.push(`# ${project.name} - ASO report - ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push("## Scope");
  lines.push("");
  lines.push("Source:");
  lines.push("");
  lines.push("```txt");
  lines.push("RespectASO (local instance, App Store / iTunes Search API data)");
  lines.push(`Tracked app id: ${project.appStoreTrackId ?? "(not configured)"}`);
  lines.push(`Configured keywords: ${(project.asoKeywords ?? []).join(", ") || "(none configured)"}`);
  lines.push(`Configured countries: ${(project.asoCountries ?? []).join(", ") || "(default: it)"}`);
  lines.push("```");
  lines.push("");

  if (latest.length === 0) {
    lines.push("No ASO keyword data found for this project yet.");
    lines.push("");
    lines.push("```txt");
    lines.push("Configure asoKeywords / asoCountries on the project, make sure RespectASO");
    lines.push("is running (`docker compose up -d`), then run `pnpm run sync:aso`.");
    lines.push("```");
    lines.push("");
    return lines.join("\n");
  }

  lines.push(`Latest data snapshot: ${latestDate}`);
  lines.push("");
  lines.push("## Keywords by opportunity score (latest snapshot)");
  lines.push("");
  lines.push("```txt");
  for (const row of latest.sort((a, b) => b.opportunityScore - a.opportunityScore)) {
    lines.push(formatKeywordRow(row));
  }
  lines.push("```");
  lines.push("");

  const previousDate = dates[dates.length - 2];
  if (previousDate) {
    const previous = keywords.filter((row) => row.date === previousDate);
    lines.push(`## Trend (${previousDate} -> ${latestDate})`);
    lines.push("");
    lines.push("```txt");
    for (const row of formatTrendRows(previous, latest)) {
      lines.push(row);
    }
    lines.push("```");
    lines.push("");
  }

  lines.push("## Breakdown by classification");
  lines.push("");
  lines.push("```txt");
  for (const [classification, rows] of [...byClassification.entries()].sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`${classification.padEnd(18)} ${rows.length} keyword(s): ${rows.map((r) => `${r.keyword} (${r.country})`).join(", ")}`);
  }
  lines.push("```");
  lines.push("");
  lines.push("## Notes");
  lines.push("");
  lines.push("```txt");
  lines.push("This is a raw data dump generated by `pnpm run report`.");
  lines.push("Classification reference:");
  lines.push("  sweet_spot       high popularity + low difficulty -> ideal target");
  lines.push("  good_target      good balance of opportunity");
  lines.push("  hidden_gem       lower popularity but very easy to rank -> niche win");
  lines.push("  high_competition high popularity but very hard -> avoid unless strong brand");
  lines.push("  moderate         average on both dimensions");
  lines.push("  low_volume       few searches -> only relevant for very niche apps");
  lines.push("  avoid            not worth targeting");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}
